#!/bin/bash
COMMIT_MSG=$1

prefix=$(head -n 1 "$COMMIT_MSG" | awk '{ print $1 }')
emoji=""
case $prefix in
    "fix:")
        emoji=":bug:"
        ;;
    "feat:")
        emoji=":sparkles:"
        ;;
    "uppkg:")
        emoji=":arrow_up:"
        ;;
    "docs:")
        emoji=":memo:"
        ;;
    "style:")
        emoji=":art:"
        ;;
    "refactor:")
        emoji=":recycle:"
        ;;
    "chore:")
        emoji=":hammer:"
        ;;
    "tag:")
        emoji=":bookmark:"
        ;;
    *)
        echo "The specified prefix is undefined."
        exit 1
        ;;
esac

awk -v prefix="$prefix" -v emoji="$emoji" 'NR==1 { sub("^" prefix, emoji); print } NR!=1' "$COMMIT_MSG" > tmpfile && mv tmpfile "$COMMIT_MSG"

echo $prefix 
exit 0
